USE Industrias_Wayne;

INSERT INTO usuarios (nome, email, senha, tipo_perfil, ativo) VALUES
('Bruce Wayne', 'bruce.wayne@wayneenterprises.com', 'senha123', 'admin_seguranca', 1),
('Lucius Fox', 'lucius.fox@wayneenterprises.com', 'senha123', 'gerente', 1),
('Alfred Pennyworth', 'alfred.pennyworth@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Barbara Gordon', 'barbara.gordon@wayneenterprises.com', 'senha123', 'gerente', 1),
('Dick Grayson', 'dick.grayson@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Jason Todd', 'jason.todd@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Tim Drake', 'tim.drake@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Damian Wayne', 'damian.wayne@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Selina Kyle', 'selina.kyle@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Harvey Bullock', 'harvey.bullock@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Jim Gordon', 'jim.gordon@wayneenterprises.com', 'senha123', 'gerente', 1),
('Renee Montoya', 'renee.montoya@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Lucia Perez', 'lucia.perez@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Marcus Vale', 'marcus.vale@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Helen Ward', 'helen.ward@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Elliot Stone', 'elliot.stone@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Nora Fields', 'nora.fields@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Victor Shaw', 'victor.shaw@wayneenterprises.com', 'senha123', 'gerente', 1),
('Lara Kent', 'lara.kent@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Connor Blake', 'connor.blake@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Mia Torres', 'mia.torres@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Ethan Cole', 'ethan.cole@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Sofia Ramos', 'sofia.ramos@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Anthony Reed', 'anthony.reed@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Chloe Martins', 'chloe.martins@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Diego Alvarez', 'diego.alvarez@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Emily Stone', 'emily.stone@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Felipe Costa', 'felipe.costa@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Giulia Nunes', 'giulia.nunes@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Hugo Carvalho', 'hugo.carvalho@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Isabela Rocha', 'isabela.rocha@wayneenterprises.com', 'senha123', 'funcionario', 1),
('João Farias', 'joao.farias@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Karina Souza', 'karina.souza@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Leonardo Lima', 'leonardo.lima@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Marina Duarte', 'marina.duarte@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Nicolas Braga', 'nicolas.braga@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Olivia Serra', 'olivia.serra@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Paulo Teixeira', 'paulo.teixeira@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Queila Araújo', 'queila.araujo@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Rafael Menezes', 'rafael.menezes@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Sara Moreira', 'sara.moreira@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Thiago Prado', 'thiago.prado@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Ursula Campos', 'ursula.campos@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Vitor Ramos', 'vitor.ramos@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Wesley Farias', 'wesley.farias@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Xavier Pinto', 'xavier.pinto@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Yasmin Lopes', 'yasmin.lopes@wayneenterprises.com', 'senha123', 'funcionario', 1),
('Zeca Andrade', 'zeca.andrade@wayneenterprises.com', 'senha123', 'funcionario', 0);


-- RECURSOS
INSERT INTO recursos (nome, categoria, descricao, status, localizacao, observacoes_adicionais) VALUES
('Servidor Central Gotham-01', 'equipamento', 'Servidor de aplicação principal do data center', 'ativo', 'Data Center - Sala 1', 'Monitorado 24/7'),
('Servidor de Backup Gotham-02', 'equipamento', 'Servidor dedicado a rotinas de backup', 'em_manutencao', 'Data Center - Sala 2', 'Revisão de discos agendada'),
('Firewall Perimetral FX-900', 'equipamento', 'Firewall de borda da rede corporativa', 'ativo', 'Sala de Redes', 'Políticas revisadas mensalmente'),
('Switch Core SW-01', 'equipamento', 'Switch core da rede interna', 'ativo', 'Sala de Redes', 'Ligado ao backbone de fibra'),
('Notebook Engenharia ENG-001', 'dispositivo', 'Notebook usado pela equipe de engenharia', 'ativo', 'Andar 5 - Engenharia', 'Acesso VPN habilitado'),
('Notebook Engenharia ENG-002', 'dispositivo', 'Notebook de campo para projetos externos', 'ativo', 'Andar 5 - Engenharia', 'Uso remoto frequente'),
('Notebook Financeiro FIN-001', 'dispositivo', 'Notebook da gerência financeira', 'ativo', 'Andar 8 - Financeiro', 'Criptografia de disco habilitada'),
('Tablet Vigilância VIG-001', 'dispositivo', 'Tablet de monitoramento de câmeras', 'ativo', 'Central de Segurança', 'Sincronizado com sistema de CFTV'),
('Smartphone Corporativo MOB-001', 'dispositivo', 'Smartphone corporativo para diretoria', 'ativo', 'Diretoria', 'Autenticação multifator obrigatória'),
('Smartphone Corporativo MOB-002', 'dispositivo', 'Smartphone corporativo para gerente de segurança', 'ativo', 'Segurança da Informação', 'Aplicativos restritos'),
('Veículo Tático VT-01', 'veiculo', 'Veículo utilitário para transporte de equipamentos', 'ativo', 'Garagem Subterrânea', 'Check-list diário obrigatório'),
('Veículo Logístico VL-02', 'veiculo', 'Veículo para entregas locais', 'em_manutencao', 'Garagem Externa', 'Revisão mecânica em andamento'),
('Veículo Executivo VX-03', 'veiculo', 'Carro executivo para Diretoria', 'ativo', 'Garagem VIP', 'Agenda de uso controlada'),
('Drone de Inspeção DR-01', 'dispositivo', 'Drone para inspeção de instalações externas', 'ativo', 'Depósito Técnico', 'Uso sob autorização prévia'),
('Câmera IP CFTV-001', 'dispositivo', 'Câmera de vigilância IP corredor leste', 'ativo', 'Corredor Leste - 3º andar', 'Integração com sistema de alertas'),
('Câmera IP CFTV-002', 'dispositivo', 'Câmera de vigilância IP entrada principal', 'ativo', 'Recepção Principal', 'Zona crítica de monitoramento'),
('Câmera IP CFTV-003', 'dispositivo', 'Câmera de vigilância IP estacionamento', 'ativo', 'Estacionamento Externo', 'Visão noturna habilitada'),
('Servidor de Banco de Dados DB-01', 'equipamento', 'Servidor dedicado a banco de dados corporativo', 'ativo', 'Data Center - Sala 1', 'Backup diário às 02h'),
('Servidor de Testes LAB-01', 'equipamento', 'Servidor ambiente de testes e homologação', 'desativado', 'Laboratório de TI', 'Substituído por nova infraestrutura'),
('Console de Acesso Remoto CON-01', 'dispositivo', 'Console para acesso remoto a servidores', 'ativo', 'NOC - Network Operations Center', 'Acesso restrito à equipe de TI'),
('Impressora de Rede PRN-01', 'dispositivo', 'Impressora de rede do setor administrativo', 'ativo', 'Andar 4 - Administrativo', 'Cotas de impressão configuradas'),
('Impressora de Rede PRN-02', 'dispositivo', 'Impressora de rede do setor jurídico', 'em_manutencao', 'Andar 7 - Jurídico', 'Troca de toner e limpeza interna'),
('Rack de Telecom RT-01', 'equipamento', 'Rack principal de telecomunicações', 'ativo', 'Sala de Telecom', 'Organização de cabos em conformidade'),
('No-break NB-01', 'equipamento', 'No-break para infraestrutura crítica', 'ativo', 'Sala de Equipamentos', 'Autonomia estimada de 45 minutos'),
('No-break NB-02', 'equipamento', 'No-break secundário para estações de trabalho', 'outro', 'Andar 5 - Engenharia', 'Uso parcial em estações específicas'),
('Scanner de Documentos SCN-01', 'dispositivo', 'Scanner de alto volume para digitalização', 'ativo', 'Arquivo Central', 'Integração com GED'),
('Projetor de Sala PROJ-01', 'dispositivo', 'Projetor multimídia sala de reuniões 1', 'ativo', 'Sala de Reuniões 1', 'Reserva via sistema interno'),
('Projetor de Sala PROJ-02', 'dispositivo', 'Projetor multimídia auditório', 'em_manutencao', 'Auditório', 'Aguardando troca de lâmpada'),
('Antena de Comunicação SAT-01', 'equipamento', 'Antena de comunicação via satélite', 'ativo', 'Cobertura do Prédio', 'Uso em situações de contingência'),
('Estação de Trabalho CAD-01', 'dispositivo', 'Workstation para modelagem 3D', 'ativo', 'Andar 5 - Engenharia', 'GPU dedicada para renderização');

-- MOVIMENTAÇÕES DE RECURSOS (INCIDENTES)
INSERT INTO movimentacoes_recursos (recurso_id, usuario_id, tipo_movimentacao) VALUES
(1, 2, 'cadastrado'),
(2, 2, 'cadastrado'),
(3, 2, 'cadastrado'),
(4, 2, 'cadastrado'),
(5, 3, 'cadastrado'),
(6, 3, 'cadastrado'),
(7, 4, 'cadastrado'),
(8, 4, 'cadastrado'),
(9, 1, 'cadastrado'),
(10, 1, 'cadastrado'),
(11, 2, 'cadastrado'),
(12, 2, 'cadastrado'),
(13, 2, 'cadastrado'),
(14, 3, 'cadastrado'),
(15, 3, 'cadastrado'),
(16, 3, 'cadastrado'),
(17, 4, 'cadastrado'),
(18, 4, 'cadastrado'),
(19, 2, 'cadastrado'),
(20, 2, 'cadastrado'),
(21, 5, 'cadastrado'),
(22, 5, 'cadastrado'),
(23, 6, 'cadastrado'),
(24, 6, 'cadastrado'),
(25, 7, 'cadastrado'),
(26, 7, 'cadastrado'),
(27, 8, 'cadastrado'),
(28, 8, 'cadastrado'),
(29, 9, 'cadastrado'),
(30, 9, 'cadastrado'),
(31, 10, 'cadastrado'),
(12, 2, 'desativado'),
(19, 2, 'desativado'),
(22, 6, 'desativado'),
(30, 9, 'desativado'),
(1, 2, 'atualizado'),
(3, 2, 'atualizado'),
(7, 4, 'atualizado'),
(11, 2, 'atualizado'),
(18, 4, 'atualizado'),
(25, 7, 'atualizado');


-- LOGS DE ACESSO (PARA CARDS E GRÁFICOS)
INSERT INTO logs_acessos (usuario_id, tipo_acao, detalhes) VALUES
(1, 'login_sucesso', 'Login via painel WTSA'),
(2, 'login_sucesso', 'Login via painel WTSA'),
(3, 'login_sucesso', 'Login via painel WTSA'),
(4, 'login_sucesso', 'Login via painel WTSA'),
(5, 'login_sucesso', 'Login via painel WTSA'),
(6, 'login_sucesso', 'Login via painel WTSA'),
(7, 'login_sucesso', 'Login via painel WTSA'),
(8, 'login_sucesso', 'Login via painel WTSA'),
(9, 'login_sucesso', 'Login via painel WTSA'),
(10, 'login_sucesso', 'Login via painel WTSA'),
(NULL, 'login_falha', 'Tentativa com email invalido@wayneenterprises.com'),
(NULL, 'login_falha', 'Tentativa com email suspeito@wayneenterprises.com'),
(NULL, 'acesso_negado', 'Usuário sem permissão tentou acessar área restrita'),
(3, 'acesso_negado', 'Tentativa de acesso a módulo de administração'),
(5, 'login_falha', 'Senha incorreta'),
(7, 'login_falha', 'Senha incorreta múltiplas vezes'),
(1, 'logout', 'Logout manual via painel'),
(2, 'logout', 'Logout automático por inatividade'),
(3, 'logout', 'Logout manual via painel'),
(4, 'logout', 'Logout manual via painel');

